my_project:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: dev
      schema: analytics
      host: dbc-88ae0a03-83ca.cloud.databricks.com
      http_path: /sql/1.0/warehouses/8260bc8671efb896
      token:
